name: CI/CD Pipeline
on:
  push:
    branches: master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ğŸš€"
        uses: actions/checkout@v4
      - name: "Cache dependencies ğŸ“"
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{runner.os}}-node_module-${{ hashFile('package*.json') }}-${{ hashFile('.github/workflows/CI-CD.yaml') }}
      - name: "Setup node âš’ï¸"
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: "Install dependencies ğŸªœ"
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm install
      - name: "Build typescript"
        run: npm run build && find dist/src/server.js
